apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: db2-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/apotitech/Openshift_Project.git'
    targetRevision: HEAD
    path: .
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: myproject
  syncPolicy:
    automated:
      prune: true
      selfHeal: true