apiVersion: apps/v1
kind: Deployment
metadata:
  name: db2-container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db2-container
  template:
    metadata:
      labels:
        app: db2-container
    spec:
      containers:
      - name: db2-container
        image: devcloudninjas/mydb:11
        ports:
        - containerPort: 50000
        env:
        - name: LICENSE
          value: "accept"
        - name: DB2INST1_PASSWORD
          value: "db2inst1"
        - name: DBNAME
          value: "testdb"
#         volumeMounts:
#         - name: db2-storage
#           mountPath: /database
#       volumes:
#       - name: db2-storage
#         persistentVolumeClaim:
#           claimName: db2-pvc
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: db2-pvc
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 10Gi
